### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:18332

### ISSUE THREAD

**Issue by bitcoinbrisbane** [Colored-Coins/colored-coins-docker-node#2]
I just keep getting Error: connect ECONNREFUSED 127.0.0.1:18332 when trying to run on testnet.

I assume in the explorer/var.env the BITCOINPORT var is the **RPCPort and not the bitcoin port?**

explorer_1  | 23/1/2017-12:13:48 - error: (11) -  Error: connect ECONNREFUSED 127.0.0.1:18332
explorer_1  |     at Object.exports._errnoException (util.js:870:11)
explorer_1  |     at exports._exceptionWithHostPort (util.js:893:20)
explorer_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

**Comment by valery-zhurbenko** [comment]
You are right. BITCOINPORT - we mean RPC, bitcoind port less important since our app not serve same bitcoind's wallet. Anyway, I updated .env files a little, to make them more understandable. 
For the bitcoind address - we assume that you have bitcoind server with opened RPC there, and you know its address, port and credentials.
I hope this help.

**Comment by bitt-john** [comment]
In the var.env try BITCOINNETWORK=172.17.0.1 ... if you do 127.0.0.1 the container will try to connect to its own localhost. Also allow this ip in your bitcoin.conf.
